### ISSUE TITLE
May I ask where the mixedudigit_dataloader and PACS_dataloader modules introduced in client.py are located？

### ISSUE THREAD

**Issue by xyxFL** [TailinZhou/FedIMA#1]
May I ask where the mixedudigit_dataloader and PACS_dataloader modules introduced in client.py are located？

**Comment by TailinZhou** [comment]
Thanks. FYI, I added the mixedudigit_dataloader and PACS_dataloader scripts a few minutes ago.

**Comment by xyxFL** [comment]
Thank you very much！
